### PR TITLE
Implement MongoClientUrl to handle parsing of values from Connection URL.

### PR DESCRIPTION
**Pull request by rayman245**
**Issues**

1. Unable to connect to MongoDB Atlas (MongoServer 4.4) due to mongo java driver version and changes in the URL structure.
2. Current implementation has custom logic for extracting information from url connection string (shards, host, port, credentials, DBName, etc), 

**Solutions For Above**

1. Updated mongodb java driver from 3.9.1 to 3.12.8
2. Implemented MongoClientUrl to do this parsing for us and create MongoClient directly. This significantly reduces bloated code and maintenance.

**Important Notes**

- Due to issue and solution 2, the localhost is now a value that needs to be provided based on specification provided by mongodb on url structure (https://docs.mongodb.com/manual/reference/connection-string/).
- Might require update on DN MongoDB documents?

### CODE REVIEW

**Comment by andyjefferson** [comment]
Thanks for the contrib. Comments
1. Presumably this will mean that any existing users code will now not work (due to the URL format). While moving to using a MongoDB "standard" connection string (which did not exist when this code was originally written) is desirable, the minimum that should happen is the user get a nice message as part of an exception saying what is wrong and what they should do.
2. Seemingly the Credential handling is not supported in this PR. Can't just throw away handling that people use.
3. [Minor] Formatting changed on header and some other bits ... for no value. Shows up in changed lines.
4. Log message(s) no longer present about connecting, but should do.
5. Using imports with "*" is not used here. Kindly fully specify all imports

**Comment by rayman245** [comment]
Hi @andyjefferson, Thanks for the review. 

**Questions..**

**1** -> Yes I agree, from my run the MongoDB driver actually does url checking and throws an exception, maybe I can just handle the exception here and and throw a DN message?

**2 & 6** -> I understand that this is a big change, but the Options and Credentials (separate authdb) can still be maintained via the uri parameters as per the url specification which should be handled by the MongoClientURI builder below.

image

Its possible to have the credentials from the storeMgr and the getMongodbOptions() work by using the following constructor   MongoClient(List<ServerAddress> seeds, MongoCredential credential, MongoClientOptions options).

Which again goes back to the complexity and extra maintenance, but could just be me over-implementing the KISS principle, do let me know what you think..

**4** -> I will add back the logs in an updated commit.

**3 & 5** -> Yep sorry about that, I think intelliJ automatically "fixes" stuff when importing, will revert in an updated commit

**Comment by andyjefferson** [comment]
For 1 I've no issue with detecting invalid URL via Mongo API and then translating it, but obviously any exception should be a NucleusException derivative, and any message should relate to the previous URL format, explaining the change. 
Functionality in issues 2 and 6 from first comment still stands

**Comment by rayman245** [comment]
@andyjefferson please review again, made changes based on last comment.

**Comment by andyjefferson** [comment]
Merged, thanks. 
Please also update the docs page for MongoDB at 
https://github.com/datanucleus/docs-accessplatform/blob/master/src/main/asciidoc/datastores/_datastores_mongodb.adoc
As a minimum refer to the MongoDB URL format and link to its docs.

**Comment by rayman245** [comment]
Sure will update the doc.

We also need to note that this implementation does not support mongodb+srv:// uri structure, so will add this to the doc as well.

Can we create feature or issue request for this? might require changes on the dn-jdo-core to accept "mongodb+srv" as a datastore.

**Comment by andyjefferson** [comment]
If you need a datastoreURL prefix of the form "mongodb+srv" to use MongoDBStoreManager then you update src/main/resources/plugin.xml accordingly ... the store_manager url-key IIRC.

**Comment by rayman245** [comment]
Yes just saw it, thanks! 

Although don't think its as simple as changing the prefix alone, might need to run some tests. I did try hardcoding that prefix and I got an error stating that the type returned was not org.mongodb.MongoClient but org.mongodb.client.MongoClient and was throwing up mapping errors.

If I have some time ill look into that.

**Pull request merged**
